### ISSUE TITLE
Build issue using Maven 3.5 (openjdk:8-jdk-alpine) - missing org.nomencurator.io.poi.ss.POIAdaptor?

### ISSUE THREAD

**Issue by mskyttner** [nomencurator/taxonaut#1]
Trying to build the Taxonaut from source with maven (using Maven 3.5 from Docker Hub based on openjdk:8-jdk-alpine) there seems to be a compilation issue related to the org.nomencurator.io.poi.ss package.

Is there missing source code for org.nomencurator.io.poi.ss.POIAdaptor? No ss directory appear to be present at https://github.com/nomencurator/taxonaut/tree/master/src/main/java/org/nomencurator/io on master branch or develop branch.

To replicate this build issue, with docker, in a new directory do:

```
# get source code
git clone https://github.com/nomencurator/taxonaut.git

# create location for mvn to cache files
mkdir -p m2

# use Docker Hub "maven:alpine" aka "maven:3.5-jdk-8-alpine" to issue "mvn compile"
docker run -it --rm --name my-maven-project \
	-v $(pwd)/taxonaut:/usr/src/mymaven \
	-v $(pwd)/m2:/root/.m2 \
	-w /usr/src/mymaven \
	maven:alpine bash -c "mvn compile -e && mvn package"
```

**Comment by mskyttner** [comment]
By the way, getting the latest release directly from GitHub Releases and running works great. 

Inspecting the release jar it appears to have the POIAdapter.class:

```
jar tf Taxonaut-3.1.7-jar-with-dependencies.jar | grep nomencurator.io.poi.ss
org/nomencurator/io/poi/ss/
org/nomencurator/io/poi/ss/POIAdaptor.class
```
Thanks for interesting paper and software!

**Comment by jmsytow** [comment]
Thanks for letting know the issue.  Sorry for long, long delay  by my misunderstanding of the issue; the jar file contains only class, of course.  The source code is now available.
